# Generated by Django 4.1.1 on 2022-09-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Priority',
            field=models.CharField(blank=True, choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=100, null=True),
        ),
    ]
