# Generated by Django 4.1.1 on 2022-09-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to='user.account'),
        ),
    ]
